# These are supported funding model platforms

github: [friendy-cheetah]
github: friendly-cheetah
custom: ['https://www.paypal.com/donate/?hosted_button_id=HQNX2K7R3MGSE']
custom: https://www.paypal.com/donate/?hosted_button_id=HQNX2K7R3MGSE
