# These are supported funding model platforms

github: [friendy-cheetah-llc]
github: friendly-cheetah-llc
custom: [https://www.paypal.com/donate/?hosted_button_id=HQNX2K7R3MGSE]
custom: https://www.paypal.com/donate/?hosted_button_id=HQNX2K7R3MGSE
